docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind

  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build -t img_teste .

test:
  stage: test
  script:
    - docker run -p 3000:3000 img_teste
  artifacts:
    paths:
      - .
